# Generated by Django 5.0.4 on 2024-05-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="blogging.post"
            ),
        ),
    ]
